### ISSUE TITLE
Where is the configuration stored?

### ISSUE THREAD

**Issue by Fxsch** [YunoHost-Apps/searxng_ynh#101]
From what I found it's supposed to be in the folder `/etc/searxng` but that folder doesn't exist

**Comment by Fxsch** [comment]
I just copied that file to `/etc/searxng/settings.yml` and that worked as well

**Comment by Fxsch** [comment]
Has something changed? SearXNG isn't using my config at `/etc/searxng/settings.yml` anymore and `/opt/yunohost/searxng` doesn't exist.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Indeed, a major refactoring happened in #113 to switch to the v2 packaging format and better follow YunoHost packaging guidelines. The settings are now available at `/var/www/searxng/settings.yml`. I'm gonna document this in the admin doc as it is not obvious. Sorry for the inconvenience.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
@Fxsch I've updated the admin doc. Please tell me if you need more info.

**Comment by Fxsch** [comment]
That's all the info I needed, thanks
