### ISSUE TITLE
Unable to backup (pre-upgrade)

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/searxng_ynh#144]
### Describe the bug

Automated pre-upgrade backup fails, thus upgrade fails

### Context

- Hardware: Hetzner 
- YunoHost version: 11.2.4
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: 2023.10.01.18.13.08~ynh1 (master branch)
- If upgrading, current package version: 2023.10.07.08.53.49~ynh1

### Steps to reproduce

- Install 2023.10.01.18.13.08~ynh1
- Update to 2023.10.07.08.53.49~ynh1
- Alternatively, perform a backup

### Expected behavior

Backups work

### Logs

https://paste.yunohost.org/raw/qicufavipi

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Hello @Aeris1One and thanks for the report. We've made quite some heavy changes recently, and it may be the cause. I'll investigate further, but if you want it fixed quickly you can try to uninstall and reinstall to upgrade while avoiding the backup process.

**Comment by Aeris1One** [comment]
Thanks, I'll do that :)

**Comment by ewilly** [comment]
Hi,
it should be fix now with 2023.10.13.10.49.52~ynh2.

**Comment by oXyiGYJ** [comment]
My issue on restore might be related to this. I did a full backup and restore, and SearxNG would not restore. Here is the paste. https://paste.yunohost.org/raw/ayoyuyikak

**Comment by mh4ckt3mh4ckt1c4s** [comment]
It seems that there is something in the package that makes the backup / restore process fails from time to time, but I cannot figure out what. I'm investigating.
