### ISSUE TITLE
Center Alignment setting is "inverted"

### ISSUE THREAD

**Issue by lucyferu** [YunoHost-Apps/searxng_ynh#28]
### Describe the bug

the Center Alignment setting in the User Interface section is somehow "inverted".
hence, when it's off, the results aligned centrally, while they don't when the setting is turned on.

### Context

- Hardware: *VPS bought online *
- YunoHost version: 11.1.17 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 2023.04.03.17.42.26~ynh1

### Steps to reproduce

just install it and do a search with the app as it comes straight out of the box (the setting is off by default) and your results will be centered.

### Expected behavior

the opposite of what is currently happening.

**Comment by dalf** [comment]
I don't know if you use a screen reader or have a custom CSS, but this is most probably related to https://github.com/searxng/searxng/issues/818 , see the line:

> Simple theme has inverted checkboxes 

The issue have to be fixed in the searxng/searxng project.

**Comment by lucyferu** [comment]
neither of those applies to me.
but, well, i guess we have to wait for them to fix it.
sorry for not checking that in advance.
and thank you  for the quick reply.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Indeed, this seems related to searxng directly, and not the yunohost package. I'll close this and you can add your report in searxng if you want. Don't hésisate to reopen if you feel the yunohost package is involved in some way.
