### ISSUE TITLE
SearXNG won't install

### ISSUE THREAD

**Issue by etieng** [YunoHost-Apps/searxng_ynh#304]
### Describe the bug

Hi, as seen [here](https://forum.yunohost.org/t/searxng-install-failure/30460), SearXNG don't install on an up to date Yunohost.
As seen in [logs](https://paste.yunohost.org/raw/roqilixuvu) the install comand `pip3 install -U pip setuptools wheel pyyaml --no-cache-dir` produce an error.
It may be a conflict between pip and system packages python library.

### Context
- Hardware: *VPS @ barebone @ home*
- YunoHost version: 11.2.21.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain:
    - ZFS raid for yunohost.app directory
    - Wireguard tunnel for an IP facing the world wide web
- Using, or trying to install package version/branch: SearXNG 2024.07.08~ynh1

### Steps to reproduce
```#: yunohost app install searxng --debug```

### Expected behavior

SearXNG should install

### Logs

see https://paste.yunohost.org/raw/roqilixuvu

**Comment by ewilly** [comment]
The issue is not in that command but in following one : `ynh_exec_fully_quiet pip3 install -e /var/www/searxng/searxng-src`
As that command is execute in fully quiet mode we can't see what is failing so the log you share can't help...
Could you please try to remove and then install (not upgrade) from the debug branch : `sudo yunohost app install https://github.com/YunoHost-Apps/searxng_ynh/tree/testing --debug`

**Comment by LukeOssevoort** [comment]
Having a similar issue on the RPi4 [Log](https://paste.yunohost.org/raw/bupavozulu)

**Comment by 32bitx64bit** [comment]
Thought it was just me, sense I'm switching over to a new hosting provider. But nope! Turns out other people are having the same issue as me.

**Comment by airjer** [comment]
> The issue is not in that command but in following one : `ynh_exec_fully_quiet pip3 install -e /var/www/searxng/searxng-src`
> 
> As that command is execute in fully quiet mode we can't see what is failing so the log you share can't help...
> 
> Could you please try to remove and then install (not upgrade) from the debug branch : `sudo yunohost app install https://github.com/YunoHost-Apps/searxng_ynh/tree/testing --debug`

https://paste.yunohost.org/raw/dewovuceru

**Comment by ewilly** [comment]
> > The issue is not in that command but in following one : `ynh_exec_fully_quiet pip3 install -e /var/www/searxng/searxng-src`
> > As that command is execute in fully quiet mode we can't see what is failing so the log you share can't help...
> > Could you please try to remove and then install (not upgrade) from the debug branch : `sudo yunohost app install https://github.com/YunoHost-Apps/searxng_ynh/tree/testing --debug`
> 
> https://paste.yunohost.org/raw/dewovuceru

ups sorry i gave you wrong command...
try `sudo yunohost app install https://github.com/YunoHost-Apps/searxng_ynh/tree/debug --debug`

**Comment by airjer** [comment]
https://paste.yunohost.org/raw/iyerugepok

**Comment by ewilly** [comment]
Tanks. Could you retry with same command and share ?

**Comment by 32bitx64bit** [comment]
> Tanks. Could you retry with same command and share ?

Hi, tried the command, installation went smoothly, everything seems to be working now.
Probably safe to push to stable.

**Comment by airjer** [comment]
Everything went through just fine. Appreciate it!

**Comment by ewilly** [comment]
Fix in 2024.07.08~ynh2
