### ISSUE TITLE
Deprecation warning when updating

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/searxng_ynh#312]
### Describe the bug

When I upgraded to 2024.07.28~ynh1 there was this deprecation message (see logs). Nevertheless, upgrade went fine and serxng works flawlessly. Just wanted to give a heads up about this.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.25
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 2024.07.28~ynh1
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

Just hit the upgrade button in webadmin.

### Expected behavior

No deprecation warning message.

### Logs

```
DEPRECATION: Legacy editable install of searxng==2024.7.28+ee959ed9f from file:///var/www/searxng/searxng-src (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
```

**Comment by ewilly** [comment]
Just a warning you can ignore
