### ISSUE TITLE
Failed to update from 2024.08.31-ynh1 to 2024.09.06-ynh1

### ISSUE THREAD

**Issue by pp-r** [YunoHost-Apps/searxng_ynh#330]
### Describe the bug

*Updating SearXNG (searxng) from 2024.08.31-ynh1 to 2024.09.06-ynh1 failed (CLI and WebAdmin).*

### Context

- Hardware: *Other 64 bit ARM board*
- YunoHost version: 11.2.30.2
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: ssh exotic port
- Using, or trying to install package version/branch: stable

### Steps to reproduce

   1. *SearXNG (searxng) de 2024.08.31-ynh1 is installed*
   2. *Click on update apps or `sudo yunohost app upgrade`*
   3. *Error: Could not upgrade searxng: An error occurred inside the app upgrade script*
   4. *SearXNG restoring and is up ... but not with the latest version 2024.09.06-ynh1*

### Expected behavior

*Update SearXNG (searxng) from 2024.08.31-ynh1 to 2024.09.06-ynh1 should work.*

### Logs

https://paste.yunohost.org/raw/asozefedew

**Comment by ewilly** [comment]
Hi,
Weird the issue appears for some but not all installations...
I try something with [e73a9c2](https://github.com/YunoHost-Apps/searxng_ynh/commit/e73a9c23981ffdf927adf140a97cfc20fa1ed1c8)
could you try to update with the following command and let me know :
`sudo yunohost app upgrade searxng -u https://github.com/YunoHost-Apps/searxng_ynh/tree/issue330 --debug`

**Comment by pp-r** [comment]
Hello,

Even if i've loosing the connexion during the updade (cli) it works : thanks !

The log :
https://paste.yunohost.org/raw/ivemiwipax
