### ISSUE TITLE
Failed to update from 2023.05.22.11.23.48~ynh1 to 2024.11.17~ynh1

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/searxng_ynh#349]
after the update to yunohost_version: 12.0.7 i just get" Internal Server Error"
and
Failed to update from 2023.05.22.11.23.48~ynh1 to 2024.11.17~ynh1

  YNH_APP_ACTION: upgrade
  YNH_APP_CURRENT_VERSION: 2023.05.22.11.23.48~ynh1
  YNH_APP_ID: searxng
  YNH_ARCH: arm64
  YNH_DEBIAN_VERSION: bookworm
  YNH_DEFAULT_PHP_VERSION: '8.2'
   yunohost_version: 12.0.7

https://paste.yunohost.org/raw/amezelilor

**Comment by ewilly** [comment]
Your version was too old : 1.5 year without updating...
I won't fix it : please uninstall and reisntall searxng
