### ISSUE TITLE
Job for [uwsgi-app@searx.service] failed

### ISSUE THREAD

**Issue by aarontrom** [YunoHost-Apps/searxng_ynh#55]
### Describe the bug

Job for [uwsgi-app@searx.service] failed because the control process exited with error code.
See "systemctl status [uwsgi-app@searx.service]" and "journalctl -xe" for details.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.1.20 (stable).
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch:

### Steps to reproduce

- Installed SearXNG via CLI, edited the config file in `/opt/yunohost/searxng/searx/settings.yml` and now I get this error message every 1 hour.

### Expected behavior

to not have this error message.

### Logs

Journalctl logs:
https://paste.yunohost.org/xuyoweseyo

```
systemctl status uwsgi-app@searx.service
● uwsgi-app@searx.service - searx uWSGI app
     Loaded: loaded (/etc/systemd/system/uwsgi-app@.service; enabled; vendor preset: enab>
     Active: failed (Result: exit-code) since Mon 2023-06-05 23:20:02 CEST; 42min ago
   Main PID: 187732 (code=exited, status=217/USER)
        CPU: 2ms
```
ll /etc/systemd/system/uwsgi-app@.service
`-rw-r--r-- 1 root root 385 Jun  5 13:38 /etc/systemd/system/uwsgi-app@.service`

less /etc/systemd/system/uwsgi-app@.service
```
[Unit]
Description=%i uWSGI app
After=syslog.target

[Service]
RuntimeDirectory=%i
ExecStart=/usr/bin/uwsgi         --ini /etc/uwsgi/apps-available/%i.ini         --socket /var/run/%i/app.socket         --logto /var/log/uwsgi/%i/%i.log
User=%i
Group=www-data
Restart=on-failure
KillSignal=SIGQUIT
Type=notify
StandardError=syslog
NotifyAccess=all

[Install]
WantedBy=multi-user.target

```

ll /usr/bin/uwsgi
`lrwxrwxrwx 1 root root 23 Jun  2 01:33 /usr/bin/uwsgi -> /etc/alternatives/uwsgi`

ll /etc/alternatives/uwsgi
`lrwxrwxrwx 1 root root 19 Jun  2 01:33 /etc/alternatives/uwsgi -> /usr/bin/uwsgi-core`

ll /usr/bin/uwsgi-core
`-rwxr-xr-x 1 root root 904K Jun 11  2021 /usr/bin/uwsgi-core`

ll /etc/uwsgi/apps-available/searxng.ini
`-rw-r--r-- 1 searxng root 1.2K Jun  5 13:38 /etc/uwsgi/apps-available/searxng.ini`

less /etc/uwsgi/apps-available/searxng.ini
```

[uwsgi]
# Who will run the code
uid = searxng
gid = searxng

# Number of workers
workers = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python3,http
lazy-apps = true
enable-threads = true

# Application base folder
base = /opt/yunohost/searxng

# Support running the module from a webserver subdirectory.
route-run = fixpathinfo:

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /opt/yunohost/searxng/venv/
pythonpath = /opt/yunohost/searxng
chdir = /opt/yunohost/searxng/searx/

# The variable holding flask application
callable = app

# speak to upstream
# -----------------

socket = /var/run/searxng/app.socket
buffer-size = 8192

# uWSGI serves the static files and in settings.yml we use::
#
#   ui:
#     static_use_hash: true
#
static-map = /static=/opt/yunohost/searxng/searx/static

# expires set to one year since there are hashes
static-expires = /* 31557600
static-gzip-all = True
offload-threads = %k

# Cache
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1

```

the .yml file for SearXNG is here:

[searxng.txt](https://github.com/YunoHost-Apps/searxng_ynh/files/11658204/searxng.txt)

Hope this helps to figure out what's wrong, I mean the instance works, it's just that I get this error message once every hour which is weird... 

If anyone has the time and the interest of looking into it, I would appreciate that :)

**Comment by mh4ckt3mh4ckt1c4s** [comment]
Do you have SearX installed ? Or did you installed it before ? The service name for SearXNG is supposed to be `uwsgi-app@searxng.service` and not `uwsgi-app@searx.service`. This error could be coming from SearX and not SearXNG. 
Could you check that you have a `uwsgi-app@searxng.service` up and running on your system ?

**Comment by aarontrom** [comment]
Ohh my gosh, I'm blind on both eyes!
Yes I switched from SearX to SearXNG, but I had a cronjob running to restart SearX every hour, because the results were not working anymore... 

I removed the cronjob, now I don't get this error message anymore of course and it is solved. 

Thanks for looking into it.
